### PR TITLE
added a set of examples

### PR DESCRIPTION
**Pull request by albemala**
added a set of examples to show how the package works. it should also increase the package score on pub.dev.

### CODE REVIEW

**Comment by albemala** [comment]
@isoos for some reason I can't add reviewers or assign the PR to you, so tagging you here

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
@albemala: thank you! are you planning anything else to add? ping me if I should publish a new release.

**Comment by albemala** [comment]
@isoos  Sure, no problem! I don't have any other changes planned at the moment, so feel free to proceed with a new release

**Comment by isoos** [comment]
published.

**Comment by albemala** [comment]
Awesome, thank you!

**Pull request merged**
